version: "3"
services:
    php_httpd:
        build:
            context: .
        restart: always
        ports:
            - 80:80
        volumes:
            - ./../:/var/www/html:z
        container_name: php_httpd
